Fixed install variations
Install now works as per TA instructions

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,10 +1,27 @@
+# #!/bin/sh
+
+# # Run npm build, and exit if it fails
+# npm run build
+# if [ $? -ne 0 ]; then
+#   exit 1
+# fi
+
+# # Run the node command
+# node dist/run.js "$@"
 #!/bin/sh
 
-# Run npm build, and exit if it fails
-npm run build
-if [ $? -ne 0 ]; then
-  exit 1
+# Check if the first argument is "install"
+
+if [ "$1" = "install" ]; then
+    echo "Running npm install..."
+    npm run build
+
+    if [ $? -ne 0 ]; then
+        echo "npm install failed. Exiting..."
+        exit 1
+    fi
+
+    exit 0
 fi
 
-# Run the node command
 node dist/run.js "$@"
