Awaiting approval (#55)
* correctness test

* correctness test 2

* correctness test 3

* Correctness Implemented

* Finished Correctness tweaking and Implemented logging

* Added npm i to startup. Ready for testing on eceprog

* Updated Readme and added the logger.ts comment header

* Update README.md

* Update README.md

* Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,2 +1,10 @@
 #!/bin/sh
+
+# Run npm build, and exit if it fails
+npm run build
+if [ $? -ne 0 ]; then
+  exit 1
+fi
+
+# Run the node command
 node dist/run.js "$@"
